#!/bin/bash -

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if ! which catt; then
    >&2 echo "Cannot find catt"
    exit 1
fi

sel=$(catt scan | rofi -dmenu)
device=$(echo $sel | awk -F'[[:blank:]]' '{print $1}')

catt -d "$device" cast "$(zenity --entry --title="cast media to" --text="URL or path of media to cast on $sel" --entry-text="$(wl-paste)")"
