#!/bin/bash -

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

output=$("$SCRIPT_DIR/cur-output")
cur_scale=$(swaymsg -t get_outputs | jq -r ".[] | select(.name==\"$output\") | .scale")
echo $cur_scale
