#!/bin/bash -

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )


output="$(swaymsg -t get_outputs | jq -r '.[] | .name' | rofi -dmenu -p 'Move workspace to output')"
swaymsg move workspace to output "$output"
swaymsg focus output "$output"
