#!/bin/bash -

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

"$SCRIPT_DIR/select-random-wallpaper" | \
    while read -r line; do
        swaymsg output '*' bg "$line" fill;
    done
