#!/bin/bash - 

img_path=${1:-~/.config/sway/config.d/local.d/bg}; 2>&1 shift

find "$img_path" -type f -exec file --mime-type {} \+ \
    | awk -F: '{if ($2 ~/image\//) print $1}' | shuf -n 1 \
    | while read -r line; do swaymsg output '*' bg "$line" fill; done
