#!/bin/bash - 

sleep_int=${1:-300}; 2>&1 shift
img_path=${1:-~/.config/sway/config.d/local.d/bg}; 2>&1 shift

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

while true; do
    "$SCRIPT_DIR"/random-wallpaper-once "${img_path}"
    sleep ${sleep_int}
done
