#!/bin/bash -

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

name=automate-workspacs.py
for prog in /usr/share/sway/scripts/"$name" "$SCRIPT_DIR/$name"; do
    if [[ -x "$prog" ]]; then
        $prog "$@"
        exit 0
    fi
done
